In [117]:
#importing basics libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [118]:
dataset = pd.read_excel("Data_Train.xlsx")

In [119]:
dataset.head(50)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
5,SpiceJet,24/06/2019,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873
6,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25 13 Mar,15h 30m,1 stop,In-flight meal not included,11087
7,Jet Airways,01/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05 02 Mar,21h 5m,1 stop,No info,22270
8,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25 13 Mar,25h 30m,1 stop,In-flight meal not included,11087
9,Multiple carriers,27/05/2019,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625
10,Air India,1/06/2019,Delhi,Cochin,DEL → BLR → COK,09:45,23:00,13h 15m,1 stop,No info,8907
11,IndiGo,18/04/2019,Kolkata,Banglore,CCU → BLR,20:20,22:55,2h 35m,non-stop,No info,4174
12,Air India,24/06/2019,Chennai,Kolkata,MAA → CCU,11:40,13:55,2h 15m,non-stop,No info,4667
13,Jet Airways,9/05/2019,Kolkata,Banglore,CCU → BOM → BLR,21:10,09:20 10 May,12h 10m,1 stop,In-flight meal not included,9663
14,IndiGo,24/04/2019,Kolkata,Banglore,CCU → BLR,17:15,19:50,2h 35m,non-stop,No info,4804
15,Air India,3/03/2019,Delhi,Cochin,DEL → AMD → BOM → COK,16:40,19:15 04 Mar,26h 35m,2 stops,No info,14011
16,SpiceJet,15/04/2019,Delhi,Cochin,DEL → PNQ → COK,08:45,13:15,4h 30m,1 stop,No info,5830
17,Jet Airways,12/06/2019,Delhi,Cochin,DEL → BOM → COK,14:00,12:35 13 Jun,22h 35m,1 stop,In-flight meal not included,10262
18,Air India,12/06/2019,Delhi,Cochin,DEL → CCU → BOM → COK,20:15,19:15 13 Jun,23h,2 stops,No info,13381
19,Jet Airways,27/05/2019,Delhi,Cochin,DEL → BOM → COK,16:00,12:35 28 May,20h 35m,1 stop,In-flight meal not included,12898
20,GoAir,6/03/2019,Delhi,Cochin,DEL → BOM → COK,14:10,19:20,5h 10m,1 stop,No info,19495
21,Air India,21/03/2019,Banglore,New Delhi,BLR → COK → DEL,22:00,13:20 19 Mar,15h 20m,1 stop,No info,6955
22,IndiGo,3/04/2019,Banglore,Delhi,BLR → DEL,04:00,06:50,2h 50m,non-stop,No info,3943
23,IndiGo,1/05/2019,Banglore,Delhi,BLR → DEL,18:55,21:50,2h 55m,non-stop,No info,4823
24,Jet Airways,6/05/2019,Kolkata,Banglore,CCU → BOM → BLR,18:55,08:15 07 May,13h 20m,1 stop,In-flight meal not included,7757
25,Jet Airways,9/06/2019,Delhi,Cochin,DEL → IDR → BOM → COK,21:25,12:35 10 Jun,15h 10m,2 stops,No info,13292
26,IndiGo,1/06/2019,Delhi,Cochin,DEL → LKO → COK,21:50,03:35 02 Jun,5h 45m,1 stop,No info,8238
27,GoAir,15/05/2019,Delhi,Cochin,DEL → BOM → COK,07:00,12:55,5h 55m,1 stop,No info,7682
28,Vistara,18/06/2019,Banglore,Delhi,BLR → DEL,09:45,12:35,2h 50m,non-stop,No info,4668
29,Vistara,15/06/2019,Chennai,Kolkata,MAA → CCU,07:05,09:20,2h 15m,non-stop,No info,3687
30,Vistara,18/06/2019,Chennai,Kolkata,MAA → CCU,07:05,09:20,2h 15m,non-stop,No info,3687
31,Air India,1/05/2019,Kolkata,Banglore,CCU → GAU → DEL → BLR,09:50,23:15,13h 25m,2 stops,No info,13227
32,IndiGo,6/04/2019,Banglore,Delhi,BLR → DEL,04:00,06:50,2h 50m,non-stop,No info,4423
33,Jet Airways,15/06/2019,Delhi,Cochin,DEL → NAG → BOM → COK,14:35,12:35 16 Jun,22h,2 stops,In-flight meal not included,10919
34,Jet Airways,18/05/2019,Delhi,Cochin,DEL → BOM → COK,07:05,12:35,5h 30m,1 stop,In-flight meal not included,12373
35,IndiGo,27/06/2019,Delhi,Cochin,DEL → BOM → COK,10:35,21:00,10h 25m,1 stop,No info,5894
36,SpiceJet,21/05/2019,Kolkata,Banglore,CCU → MAA → BLR,15:05,20:20,5h 15m,1 stop,No info,4649
37,Air India,18/05/2019,Kolkata,Banglore,CCU → BLR,14:15,16:45,2h 30m,non-stop,No info,6245
38,Jet Airways,06/03/2019,Banglore,New Delhi,BLR → BOM → DEL,07:00,13:15,6h 15m,1 stop,No info,19225
39,Jet Airways,3/06/2019,Delhi,Cochin,DEL → BOM → COK,07:05,19:00,11h 55m,1 stop,No info,14924
40,Multiple carriers,21/05/2019,Delhi,Cochin,DEL → HYD → COK,07:05,18:10,11h 5m,1 stop,No info,9646
41,Air India,15/03/2019,Banglore,New Delhi,BLR → BOM → DEL,06:45,15:15,8h 30m,1 stop,No info,8714
42,Jet Airways,18/05/2019,Delhi,Cochin,DEL → BOM → COK,20:55,19:00 19 May,22h 5m,1 stop,In-flight meal not included,12373
43,Air Asia,6/05/2019,Banglore,Delhi,BLR → DEL,11:10,13:55,2h 45m,non-stop,No info,3383
44,Multiple carriers,21/03/2019,Delhi,Cochin,DEL → BOM → COK,09:00,21:00,12h,1 stop,No info,13062
45,SpiceJet,24/03/2019,Banglore,New Delhi,BLR → DEL,05:45,08:35,2h 50m,non-stop,No check-in baggage included,3527
46,IndiGo,27/05/2019,Banglore,Delhi,BLR → DEL,04:00,06:50,2h 50m,non-stop,No info,3943
47,Air India,3/05/2019,Chennai,Kolkata,MAA → CCU,11:40,13:55,2h 15m,non-stop,No info,4667
48,Air India,15/05/2019,Kolkata,Banglore,CCU → HYD → BLR,19:00,11:05 16 May,16h 5m,1 stop,No info,6117
49,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150

In [120]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [121]:
# dataset["Date"] = dataset["Date_of_Journey"].str.split("/").str[0]
# dataset["Month"] = dataset["Date_of_Journey"].str.split("/").str[1]
# dataset['Year'] = dataset['Date_of_Journey'].str.split("/").str[2] 
# dataset[["Date","Month","Year"]] = dataset['Date_of_Journey'].apply(lambda x:pd.Series(x.split("/")))
dataset[["Date","Month","Year"]] = dataset["Date_of_Journey"].str.split('/',expand=True)
# dataset

In [122]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  object
 12  Month            10683 non-null  object
 13  Year             10683 non-null  object
dtypes: int64(1), object(13)
memory usage: 1.1+ MB

In [123]:
#now convert object to int whatever we splited values
# # dataset["Date"] = dataset['Date'].astype(int)
# dataset[["Date","Month","Year"]] = dataset[["Date","Month","Year"]].apply(lambda x : x.astype(int))
dataset[["Date","Month","Year"]] = dataset[["Date","Month","Year"]].astype(int)
# dataset.info()

In [124]:
#now main feature should be drop after split from there
dataset.drop(columns="Date_of_Journey", inplace=True,axis=1)

In [125]:
dataset['Arrival_Time'] = dataset["Arrival_Time"].str.split(" ").str[0]
dataset['Arrival_Time']

0        01:10
1        13:15
2        04:25
3        23:30
4        21:35
         ...
10678    22:25
10679    23:20
10680    11:20
10681    14:10
10682    19:15
Name: Arrival_Time, Length: 10683, dtype: object

In [126]:
dataset[["Arrival_hour","Arrival_minutes"]] = dataset['Arrival_Time'].str.split(":",expand=True).astype(int)
dataset.drop(columns="Arrival_Time")
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  Month            10683 non-null  int64
 12  Year             10683 non-null  int64
 13  Arrival_hour     10683 non-null  int64
 14  Arrival_minutes  10683 non-null  int64
dtypes: int64(6), object(9)
memory usage: 1.2+ MB

In [127]:
# dataset[["Dep_hour","Dep_min"]] = dataset['Dep_Time'].apply(lambda x:pd.Series(x.split(":"))).astype(int)
dataset[["Dep_hour","Dep_min"]] = dataset['Dep_Time'].str.split(":",expand=True).astype(int)
dataset.drop("Dep_Time",inplace=True,axis=1)

In [128]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Arrival_Time     10683 non-null  object
 5   Duration         10683 non-null  object
 6   Total_Stops      10682 non-null  object
 7   Additional_Info  10683 non-null  object
 8   Price            10683 non-null  int64
 9   Date             10683 non-null  int64
 10  Month            10683 non-null  int64
 11  Year             10683 non-null  int64
 12  Arrival_hour     10683 non-null  int64
 13  Arrival_minutes  10683 non-null  int64
 14  Dep_hour         10683 non-null  int64
 15  Dep_min          10683 non-null  int64
dtypes: int64(8), object(8)
memory usage: 1.3+ MB

In [129]:
# dataset['Duration_hour'] = dataset['Duration'].str.split(' ').str[0].str.split('h').str[0].astype(int)
dataset[dataset['Duration']=='5m']
dataset.drop(6474,inplace=True,axis=0)

In [130]:
dataset.isnull().sum()

Airline            0
Source             0
Destination        0
Route              1
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
Date               0
Month              0
Year               0
Arrival_hour       0
Arrival_minutes    0
Dep_hour           0
Dep_min            0
dtype: int64

In [134]:
# dataset[dataset['Duration_hour']=='5m']
duration_hour = dataset['Duration'].str.split(' ').str[0].str.split('h').str[0].astype(int)
duration_min  = dataset["Duration"].str.split(' ').str[1].str.split('m').str[0]
duration_min = duration_time.fillna(0)
duration_min = duration_min.astype(int)
dataset["Duration_minutes"] = (duration_hour)*60 + duration_min
dataset["Duration_minutes"]
# dataset["Duration_hour"] = dataset['Duration_hour'].astype(int)

0         170
1         445
2        1140
3         325
4         285
         ...
10678     150
10679     155
10680     180
10681     160
10682     500
Name: Duration_minutes, Length: 10682, dtype: int64

In [132]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           10682 non-null  object
 1   Source            10682 non-null  object
 2   Destination       10682 non-null  object
 3   Route             10681 non-null  object
 4   Arrival_Time      10682 non-null  object
 5   Duration          10682 non-null  object
 6   Total_Stops       10681 non-null  object
 7   Additional_Info   10682 non-null  object
 8   Price             10682 non-null  int64
 9   Date              10682 non-null  int64
 10  Month             10682 non-null  int64
 11  Year              10682 non-null  int64
 12  Arrival_hour      10682 non-null  int64
 13  Arrival_minutes   10682 non-null  int64
 14  Dep_hour          10682 non-null  int64
 15  Dep_min           10682 non-null  int64
 16  Duration_minutes  10682 non-null  int64
dtypes: int64(9), object(8)
memory usage: 1.5+ MB

In [ ]:
dataset.drop("Duration",inplace=True,axis=1)

In [136]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           10682 non-null  object
 1   Source            10682 non-null  object
 2   Destination       10682 non-null  object
 3   Route             10681 non-null  object
 4   Arrival_Time      10682 non-null  object
 5   Total_Stops       10681 non-null  object
 6   Additional_Info   10682 non-null  object
 7   Price             10682 non-null  int64
 8   Date              10682 non-null  int64
 9   Month             10682 non-null  int64
 10  Year              10682 non-null  int64
 11  Arrival_hour      10682 non-null  int64
 12  Arrival_minutes   10682 non-null  int64
 13  Dep_hour          10682 non-null  int64
 14  Dep_min           10682 non-null  int64
 15  Duration_minutes  10682 non-null  int64
dtypes: int64(9), object(7)
memory usage: 1.4+ MB

In [141]:
dataset["Total_Stops"].value_counts()
dataset['Total_Stops']

0        non-stop
1         2 stops
2         2 stops
3          1 stop
4          1 stop
           ...
10678    non-stop
10679    non-stop
10680    non-stop
10681    non-stop
10682     2 stops
Name: Total_Stops, Length: 10682, dtype: object

In [143]:
dataset['Total_Stops'] = dataset['Total_Stops'].map({"1 stop":1,"non-stop":0,"2 stops":2,"3 stops":3,"4 stops":4,"NaN":1})

In [145]:
dataset

,Airline,Source,Destination,Route,Arrival_Time,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minutes,Dep_hour,Dep_min,Duration_minutes
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10,0.0,No info,3897,24,3,2019,1,10,22,20,170
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,2.0,No info,7662,1,5,2019,13,15,5,50,445
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,04:25,2.0,No info,13882,9,6,2019,4,25,9,25,1140
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,23:30,1.0,No info,6218,12,5,2019,23,30,18,5,325
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,21:35,1.0,No info,13302,1,3,2019,21,35,16,50,285
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,22:25,0.0,No info,4107,9,4,2019,22,25,19,55,150
10679,Air India,Kolkata,Banglore,CCU → BLR,23:20,0.0,No info,4145,27,4,2019,23,20,20,45,155
10680,Jet Airways,Banglore,Delhi,BLR → DEL,11:20,0.0,No info,7229,27,4,2019,11,20,8,20,180
10681,Vistara,Banglore,New Delhi,BLR → DEL,14:10,0.0,No info,12648,1,3,2019,14,10,11,30,160
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,19:15,2.0,No info,11753,9,5,2019,19,15,10,55,500

In [147]:
dataset.drop("Route",inplace=True,axis=1)

In [148]:
dataset.head()

,Airline,Source,Destination,Arrival_Time,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minutes,Dep_hour,Dep_min,Duration_minutes
0,IndiGo,Banglore,New Delhi,01:10,0.0,No info,3897,24,3,2019,1,10,22,20,170
1,Air India,Kolkata,Banglore,13:15,2.0,No info,7662,1,5,2019,13,15,5,50,445
2,Jet Airways,Delhi,Cochin,04:25,2.0,No info,13882,9,6,2019,4,25,9,25,1140
3,IndiGo,Kolkata,Banglore,23:30,1.0,No info,6218,12,5,2019,23,30,18,5,325
4,IndiGo,Banglore,New Delhi,21:35,1.0,No info,13302,1,3,2019,21,35,16,50,285

In [150]:
dataset["Airline"].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1751
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [153]:
dataset["Source"].value_counts().sort_values(ascending=False)

Source
Delhi       4537
Kolkata     2871
Banglore    2197
Mumbai       696
Chennai      381
Name: count, dtype: int64

In [154]:
dataset["Destination"].value_counts().sort_values(ascending=False)

Destination
Cochin       4537
Banglore     2871
Delhi        1265
New Delhi     932
Hyderabad     696
Kolkata       381
Name: count, dtype: int64

In [155]:
dataset['Additional_Info'].value_counts()

Additional_Info
No info                         8344
In-flight meal not included     1982
No check-in baggage included     320
1 Long layover                    19
Change airports                    7
Business class                     4
No Info                            3
1 Short layover                    1
Red-eye flight                     1
2 Long layover                     1
Name: count, dtype: int64

In [160]:
pd.get_dummies(dataset,columns=["Airline","Source","Destination","Additional_Info"],drop_first=True)

,Arrival_Time,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_minutes,Dep_hour,Dep_min,...,Destination_New Delhi,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,01:10,0.0,3897,24,3,2019,1,10,22,20,...,True,False,False,False,False,False,False,False,True,False
1,13:15,2.0,7662,1,5,2019,13,15,5,50,...,False,False,False,False,False,False,False,False,True,False
2,04:25,2.0,13882,9,6,2019,4,25,9,25,...,False,False,False,False,False,False,False,False,True,False
3,23:30,1.0,6218,12,5,2019,23,30,18,5,...,False,False,False,False,False,False,False,False,True,False
4,21:35,1.0,13302,1,3,2019,21,35,16,50,...,True,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,22:25,0.0,4107,9,4,2019,22,25,19,55,...,False,False,False,False,False,False,False,False,True,False
10679,23:20,0.0,4145,27,4,2019,23,20,20,45,...,False,False,False,False,False,False,False,False,True,False
10680,11:20,0.0,7229,27,4,2019,11,20,8,20,...,False,False,False,False,False,False,False,False,True,False
10681,14:10,0.0,12648,1,3,2019,14,10,11,30,...,True,False,False,False,False,False,False,False,True,False
10682,19:15,2.0,11753,9,5,2019,19,15,10,55,...,False,False,False,False,False,False,False,False,True,False